zookeeper:
  image: wurstmeister/zookeeper
  ports: 
    - "2181:2181"
kafka:
  image: sweetspot/kafka:0.1
  ports:
    - "9092:9092"
  links: 
    - zookeeper:zk
  environment:
    KAFKA_ADVERTISED_HOST_NAME: 192.168.59.103
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
